import globals from "globals";

export default [
  {
    files: ["js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,

        // ── main.js ──
        TOAST_DURATION_MS: "readonly",
        UNDO_MAX_HISTORY: "readonly",
        LOG_MAX_ENTRIES: "readonly",
        PREFS_MAX_THRESHOLD: "readonly",
        PREFS_MIN_THRESHOLD: "readonly",
        STOCK_COLOR_STOPS: "readonly",
        Events: "readonly",
        EventBus: "readonly",
        UndoRedo: "readonly",
        App: "writable",
        AppLog: "readonly",
        showToast: "readonly",
        escHtml: "readonly",
        api: "readonly",
        Modal: "readonly",
        setupDropZone: "readonly",
        resetDropZoneInput: "readonly",
        linkPriceInputs: "readonly",
        loadPreferences: "readonly",
        savePreferences: "readonly",
        getThreshold: "readonly",
        setThreshold: "readonly",
        stockValueColor: "readonly",
        prefsModal: "readonly",
        openPreferencesModal: "readonly",
        closePreferencesModal: "readonly",
        applyPreferences: "readonly",
        updateSliderTrack: "readonly",
        updateInventoryHeader: "readonly",
        loadInventory: "readonly",
        onInventoryUpdated: "readonly",
        closeModal: "readonly",
        handleWindowClose: "readonly",
        snapshotLinks: "readonly",
        initApp: "readonly",

        // ── csv-parser.js ──
        parseCSV: "readonly",
        detectBOMColumns: "readonly",
        extractLCSC: "readonly",
        isDnp: "readonly",
        extractPartIds: "readonly",
        generateCSV: "readonly",
        aggregateBomRows: "readonly",
        processBOM: "readonly",

        // ── part-keys.js ──
        STATUS_ICONS: "readonly",
        STATUS_ROW_CLASS: "readonly",
        countStatuses: "readonly",
        bomKey: "readonly",
        bomAggKey: "readonly",
        invPartKey: "readonly",
        rawRowAggKey: "readonly",

        // ── bom-row-data.js ──
        bomRowDisplayData: "readonly",

        // ── matching.js ──
        VALUE_TOLERANCE: "readonly",
        MPN_PREFIX_MIN_LEN: "readonly",
        MPN_FUZZY_MIN_LEN: "readonly",
        MPN_FUZZY_MIN_RATIO: "readonly",
        getMult: "readonly",
        parseEEValue: "readonly",
        extractValueFromDesc: "readonly",
        extractBomValue: "readonly",
        componentTypeFromRefs: "readonly",
        componentTypeFromSection: "readonly",
        isPassiveSection: "readonly",
        packagesCompatible: "readonly",
        valuesCompatible: "readonly",
        isFuzzyMatchValid: "readonly",
        valueKey: "readonly",
        buildLookupMaps: "readonly",
        findValueMatch: "readonly",
        findAlternatives: "readonly",
        matchBOM: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { vars: "local", args: "none" }],
    },
  },
];
