"""AUTO-GENERATED — do not edit by hand.

Source of truth: docs/openapi-v1.json
Regenerate: python scripts/gen-cli.py
"""

COMMANDS = {'adjustments remove-last': {'bodyParams': [],
                             'httpVerb': 'DELETE',
                             'operationId': 'remove_last_adjustments',
                             'params': {'count': {'required': True, 'type': 'integer'}},
                             'path': '/v1/adjustments/last',
                             'pathParams': [],
                             'queryParams': ['count'],
                             'rawBody': False,
                             'resource': 'adjustments',
                             'unwrap': 'detail',
                             'verb': 'remove-last',
                             'writes': True},
 'adjustments rollback-source': {'bodyParams': [],
                                 'httpVerb': 'DELETE',
                                 'operationId': 'rollback_source',
                                 'params': {'source': {'required': True, 'type': 'string'}},
                                 'path': '/v1/adjustments/by-source/{source}',
                                 'pathParams': ['source'],
                                 'queryParams': [],
                                 'rawBody': False,
                                 'resource': 'adjustments',
                                 'unwrap': 'detail',
                                 'verb': 'rollback-source',
                                 'writes': True},
 'bom consume': {'bodyParams': ['board_qty', 'bom_name', 'matches', 'note', 'source'],
                 'httpVerb': 'POST',
                 'operationId': 'consume_bom',
                 'params': {'board_qty': {'required': True, 'type': 'integer'},
                            'bom_name': {'required': True, 'type': 'string'},
                            'matches': {'required': True, 'type': 'array'},
                            'note': {'required': False, 'type': 'string'},
                            'source': {'required': False, 'type': 'string'}},
                 'path': '/v1/bom/consume',
                 'pathParams': [],
                 'queryParams': [],
                 'rawBody': False,
                 'resource': 'bom',
                 'unwrap': 'detail',
                 'verb': 'consume',
                 'writes': True},
 'bom resolve-spec': {'bodyParams': ['package', 'part_type', 'value'],
                      'httpVerb': 'POST',
                      'operationId': 'resolve_bom_spec',
                      'params': {'package': {'required': True, 'type': 'string'},
                                 'part_type': {'required': True, 'type': 'string'},
                                 'value': {'required': True, 'type': 'number'}},
                      'path': '/v1/bom/resolve-spec',
                      'pathParams': [],
                      'queryParams': [],
                      'rawBody': False,
                      'resource': 'bom',
                      'unwrap': 'match',
                      'verb': 'resolve-spec',
                      'writes': True},
 'carts add-bom-missing': {'bodyParams': ['missing'],
                           'httpVerb': 'POST',
                           'operationId': 'add_bom_missing_to_cart',
                           'params': {'cart_id': {'required': True, 'type': 'string'},
                                      'missing': {'required': True, 'type': 'array'}},
                           'path': '/v1/carts/{cart_id}/add-bom-missing',
                           'pathParams': ['cart_id'],
                           'queryParams': [],
                           'rawBody': False,
                           'resource': 'carts',
                           'unwrap': 'detail',
                           'verb': 'add-bom-missing',
                           'writes': True},
 'carts add-item': {'bodyParams': ['part_id',
                                   'per_board_qty',
                                   'preset',
                                   'qty',
                                   'raw',
                                   'shortfall',
                                   'target_distributor',
                                   'target_packaging'],
                    'httpVerb': 'POST',
                    'operationId': 'add_cart_item',
                    'params': {'cart_id': {'required': True, 'type': 'string'},
                               'part_id': {'required': False, 'type': 'string'},
                               'per_board_qty': {'required': False, 'type': 'integer'},
                               'preset': {'required': False, 'type': 'string'},
                               'qty': {'required': False, 'type': 'integer'},
                               'raw': {'required': False, 'type': 'object'},
                               'shortfall': {'required': False, 'type': 'integer'},
                               'target_distributor': {'required': False, 'type': 'string'},
                               'target_packaging': {'required': False, 'type': 'string'}},
                    'path': '/v1/carts/{cart_id}/items',
                    'pathParams': ['cart_id'],
                    'queryParams': [],
                    'rawBody': False,
                    'resource': 'carts',
                    'unwrap': 'detail',
                    'verb': 'add-item',
                    'writes': True},
 'carts clear': {'bodyParams': [],
                 'httpVerb': 'POST',
                 'operationId': 'clear_cart',
                 'params': {'cart_id': {'required': True, 'type': 'string'}},
                 'path': '/v1/carts/{cart_id}/clear',
                 'pathParams': ['cart_id'],
                 'queryParams': [],
                 'rawBody': False,
                 'resource': 'carts',
                 'unwrap': 'detail',
                 'verb': 'clear',
                 'writes': True},
 'carts consolidate': {'bodyParams': ['distributor'],
                       'httpVerb': 'POST',
                       'operationId': 'consolidate_cart',
                       'params': {'cart_id': {'required': True, 'type': 'string'},
                                  'distributor': {'required': True, 'type': 'string'}},
                       'path': '/v1/carts/{cart_id}/consolidate',
                       'pathParams': ['cart_id'],
                       'queryParams': [],
                       'rawBody': False,
                       'resource': 'carts',
                       'unwrap': 'detail',
                       'verb': 'consolidate',
                       'writes': True},
 'carts create': {'bodyParams': ['name'],
                  'httpVerb': 'POST',
                  'operationId': 'create_cart',
                  'params': {'name': {'required': False, 'type': 'string'}},
                  'path': '/v1/carts',
                  'pathParams': [],
                  'queryParams': [],
                  'rawBody': False,
                  'resource': 'carts',
                  'unwrap': 'detail',
                  'verb': 'create',
                  'writes': True},
 'carts delete': {'bodyParams': [],
                  'httpVerb': 'DELETE',
                  'operationId': 'delete_cart',
                  'params': {'cart_id': {'required': True, 'type': 'string'}},
                  'path': '/v1/carts/{cart_id}',
                  'pathParams': ['cart_id'],
                  'queryParams': [],
                  'rawBody': False,
                  'resource': 'carts',
                  'unwrap': 'detail',
                  'verb': 'delete',
                  'writes': True},
 'carts export': {'bodyParams': [],
                  'httpVerb': 'GET',
                  'operationId': 'export_cart',
                  'params': {'cart_id': {'required': True, 'type': 'string'},
                             'distributor': {'required': True, 'type': 'string'},
                             'format': {'required': False, 'type': 'string'}},
                  'path': '/v1/carts/{cart_id}/export',
                  'pathParams': ['cart_id'],
                  'queryParams': ['distributor', 'format'],
                  'rawBody': False,
                  'resource': 'carts',
                  'unwrap': None,
                  'verb': 'export',
                  'writes': False},
 'carts get': {'bodyParams': [],
               'httpVerb': 'GET',
               'operationId': 'get_cart',
               'params': {'cart_id': {'required': True, 'type': 'string'}},
               'path': '/v1/carts/{cart_id}',
               'pathParams': ['cart_id'],
               'queryParams': [],
               'rawBody': False,
               'resource': 'carts',
               'unwrap': None,
               'verb': 'get',
               'writes': False},
 'carts list': {'bodyParams': [],
                'httpVerb': 'GET',
                'operationId': 'list_carts',
                'params': {},
                'path': '/v1/carts',
                'pathParams': [],
                'queryParams': [],
                'rawBody': False,
                'resource': 'carts',
                'unwrap': None,
                'verb': 'list',
                'writes': False},
 'carts plan': {'bodyParams': [],
                'httpVerb': 'GET',
                'operationId': 'plan_cart',
                'params': {'cart_id': {'required': True, 'type': 'string'},
                           'preset': {'required': False, 'type': 'string'},
                           'reel_ceiling': {'required': False, 'type': 'number'}},
                'path': '/v1/carts/{cart_id}/plan',
                'pathParams': ['cart_id'],
                'queryParams': ['preset', 'reel_ceiling'],
                'rawBody': False,
                'resource': 'carts',
                'unwrap': None,
                'verb': 'plan',
                'writes': False},
 'carts remove-item': {'bodyParams': [],
                       'httpVerb': 'DELETE',
                       'operationId': 'remove_cart_item',
                       'params': {'cart_id': {'required': True, 'type': 'string'},
                                  'ref': {'required': True, 'type': 'string'}},
                       'path': '/v1/carts/{cart_id}/items/{ref}',
                       'pathParams': ['cart_id', 'ref'],
                       'queryParams': [],
                       'rawBody': False,
                       'resource': 'carts',
                       'unwrap': 'detail',
                       'verb': 'remove-item',
                       'writes': True},
 'carts rename': {'bodyParams': ['name'],
                  'httpVerb': 'PUT',
                  'operationId': 'rename_cart',
                  'params': {'cart_id': {'required': True, 'type': 'string'},
                             'name': {'required': True, 'type': 'string'}},
                  'path': '/v1/carts/{cart_id}',
                  'pathParams': ['cart_id'],
                  'queryParams': [],
                  'rawBody': False,
                  'resource': 'carts',
                  'unwrap': 'detail',
                  'verb': 'rename',
                  'writes': True},
 'carts set-active': {'bodyParams': [],
                      'httpVerb': 'POST',
                      'operationId': 'set_active_cart',
                      'params': {'cart_id': {'required': True, 'type': 'string'}},
                      'path': '/v1/carts/{cart_id}/active',
                      'pathParams': ['cart_id'],
                      'queryParams': [],
                      'rawBody': False,
                      'resource': 'carts',
                      'unwrap': 'detail',
                      'verb': 'set-active',
                      'writes': True},
 'carts set-board-count': {'bodyParams': ['board_count'],
                           'httpVerb': 'PUT',
                           'operationId': 'set_cart_board_count',
                           'params': {'board_count': {'required': True, 'type': 'integer'},
                                      'cart_id': {'required': True, 'type': 'string'}},
                           'path': '/v1/carts/{cart_id}/board-count',
                           'pathParams': ['cart_id'],
                           'queryParams': [],
                           'rawBody': False,
                           'resource': 'carts',
                           'unwrap': 'detail',
                           'verb': 'set-board-count',
                           'writes': True},
 'carts split': {'bodyParams': ['distributor', 'new_name', 'remove_from_source'],
                 'httpVerb': 'POST',
                 'operationId': 'split_cart',
                 'params': {'cart_id': {'required': True, 'type': 'string'},
                            'distributor': {'required': True, 'type': 'string'},
                            'new_name': {'required': True, 'type': 'string'},
                            'remove_from_source': {'required': False, 'type': 'boolean'}},
                 'path': '/v1/carts/{cart_id}/split',
                 'pathParams': ['cart_id'],
                 'queryParams': [],
                 'rawBody': False,
                 'resource': 'carts',
                 'unwrap': 'detail',
                 'verb': 'split',
                 'writes': True},
 'carts update-item': {'bodyParams': ['per_board_qty',
                                      'preset',
                                      'qty',
                                      'target_distributor',
                                      'target_packaging'],
                       'httpVerb': 'PATCH',
                       'operationId': 'update_cart_item',
                       'params': {'cart_id': {'required': True, 'type': 'string'},
                                  'per_board_qty': {'required': False, 'type': 'integer'},
                                  'preset': {'required': False, 'type': 'string'},
                                  'qty': {'required': False, 'type': 'integer'},
                                  'ref': {'required': True, 'type': 'string'},
                                  'target_distributor': {'required': False, 'type': 'string'},
                                  'target_packaging': {'required': False, 'type': 'string'}},
                       'path': '/v1/carts/{cart_id}/items/{ref}',
                       'pathParams': ['cart_id', 'ref'],
                       'queryParams': [],
                       'rawBody': False,
                       'resource': 'carts',
                       'unwrap': 'detail',
                       'verb': 'update-item',
                       'writes': True},
 'distributors clear-mouser-api-key': {'bodyParams': [],
                                       'httpVerb': 'DELETE',
                                       'operationId': 'clear_mouser_api_key',
                                       'params': {},
                                       'path': '/v1/distributors/mouser/key',
                                       'pathParams': [],
                                       'queryParams': [],
                                       'rawBody': False,
                                       'resource': 'distributors',
                                       'unwrap': None,
                                       'verb': 'clear-mouser-api-key',
                                       'writes': True},
 'distributors fetch-product': {'bodyParams': [],
                                'httpVerb': 'GET',
                                'operationId': 'fetch_distributor_product',
                                'params': {'code': {'required': True, 'type': 'string'},
                                           'name': {'required': True, 'type': 'string'}},
                                'path': '/v1/distributors/{name}/product/{code}',
                                'pathParams': ['name', 'code'],
                                'queryParams': [],
                                'rawBody': False,
                                'resource': 'distributors',
                                'unwrap': None,
                                'verb': 'fetch-product',
                                'writes': False},
 'distributors get-digikey-session': {'bodyParams': [],
                                      'httpVerb': 'GET',
                                      'operationId': 'get_digikey_session',
                                      'params': {},
                                      'path': '/v1/distributors/digikey/session',
                                      'pathParams': [],
                                      'queryParams': [],
                                      'rawBody': False,
                                      'resource': 'distributors',
                                      'unwrap': None,
                                      'verb': 'get-digikey-session',
                                      'writes': False},
 'distributors get-mouser-api-key-status': {'bodyParams': [],
                                            'httpVerb': 'GET',
                                            'operationId': 'get_mouser_api_key_status',
                                            'params': {},
                                            'path': '/v1/distributors/mouser/key',
                                            'pathParams': [],
                                            'queryParams': [],
                                            'rawBody': False,
                                            'resource': 'distributors',
                                            'unwrap': None,
                                            'verb': 'get-mouser-api-key-status',
                                            'writes': False},
 'distributors logout-digikey': {'bodyParams': [],
                                 'httpVerb': 'DELETE',
                                 'operationId': 'logout_digikey',
                                 'params': {},
                                 'path': '/v1/distributors/digikey/session',
                                 'pathParams': [],
                                 'queryParams': [],
                                 'rawBody': False,
                                 'resource': 'distributors',
                                 'unwrap': None,
                                 'verb': 'logout-digikey',
                                 'writes': True},
 'distributors set-mouser-api-key': {'bodyParams': ['key'],
                                     'httpVerb': 'PUT',
                                     'operationId': 'set_mouser_api_key',
                                     'params': {'key': {'required': True, 'type': 'string'}},
                                     'path': '/v1/distributors/mouser/key',
                                     'pathParams': [],
                                     'queryParams': [],
                                     'rawBody': False,
                                     'resource': 'distributors',
                                     'unwrap': None,
                                     'verb': 'set-mouser-api-key',
                                     'writes': True},
 'distributors sync-digikey-cookies': {'bodyParams': [],
                                       'httpVerb': 'POST',
                                       'operationId': 'sync_digikey_cookies',
                                       'params': {},
                                       'path': '/v1/distributors/digikey/cookies/sync',
                                       'pathParams': [],
                                       'queryParams': [],
                                       'rawBody': False,
                                       'resource': 'distributors',
                                       'unwrap': None,
                                       'verb': 'sync-digikey-cookies',
                                       'writes': True},
 'distributors validate-digikey-session': {'bodyParams': [],
                                           'httpVerb': 'POST',
                                           'operationId': 'validate_digikey_session',
                                           'params': {},
                                           'path': '/v1/distributors/digikey/session/validate',
                                           'pathParams': [],
                                           'queryParams': [],
                                           'rawBody': False,
                                           'resource': 'distributors',
                                           'unwrap': None,
                                           'verb': 'validate-digikey-session',
                                           'writes': True},
 'feeders get': {'bodyParams': [],
                 'httpVerb': 'GET',
                 'operationId': 'get_feeder',
                 'params': {'tag_id': {'required': True, 'type': 'string'}},
                 'path': '/v1/feeders/{tag_id}',
                 'pathParams': ['tag_id'],
                 'queryParams': [],
                 'rawBody': False,
                 'resource': 'feeders',
                 'unwrap': None,
                 'verb': 'get',
                 'writes': False},
 'feeders list': {'bodyParams': [],
                  'httpVerb': 'GET',
                  'operationId': 'list_feeders',
                  'params': {},
                  'path': '/v1/feeders',
                  'pathParams': [],
                  'queryParams': [],
                  'rawBody': False,
                  'resource': 'feeders',
                  'unwrap': None,
                  'verb': 'list',
                  'writes': False},
 'feeders load-reel': {'bodyParams': ['part_key', 'qty', 'tape_width_mm'],
                       'httpVerb': 'POST',
                       'operationId': 'load_feeder_reel',
                       'params': {'part_key': {'required': True, 'type': 'string'},
                                  'qty': {'required': True, 'type': 'integer'},
                                  'tag_id': {'required': True, 'type': 'string'},
                                  'tape_width_mm': {'required': False, 'type': 'number'}},
                       'path': '/v1/feeders/{tag_id}/load',
                       'pathParams': ['tag_id'],
                       'queryParams': [],
                       'rawBody': False,
                       'resource': 'feeders',
                       'unwrap': None,
                       'verb': 'load-reel',
                       'writes': True},
 'feeders register': {'bodyParams': ['feeder_type'],
                      'httpVerb': 'POST',
                      'operationId': 'register_feeder',
                      'params': {'feeder_type': {'required': True, 'type': 'string'},
                                 'tag_id': {'required': True, 'type': 'string'}},
                      'path': '/v1/feeders/{tag_id}/register',
                      'pathParams': ['tag_id'],
                      'queryParams': [],
                      'rawBody': False,
                      'resource': 'feeders',
                      'unwrap': None,
                      'verb': 'register',
                      'writes': True},
 'feeders unload': {'bodyParams': [],
                    'httpVerb': 'POST',
                    'operationId': 'unload_feeder',
                    'params': {'tag_id': {'required': True, 'type': 'string'}},
                    'path': '/v1/feeders/{tag_id}/unload',
                    'pathParams': ['tag_id'],
                    'queryParams': [],
                    'rawBody': False,
                    'resource': 'feeders',
                    'unwrap': None,
                    'verb': 'unload',
                    'writes': True},
 'generic add-member': {'bodyParams': ['part_id'],
                        'httpVerb': 'POST',
                        'operationId': 'add_generic_member',
                        'params': {'generic_part_id': {'required': True, 'type': 'string'},
                                   'part_id': {'required': True, 'type': 'string'}},
                        'path': '/v1/generic-parts/{generic_part_id}/members',
                        'pathParams': ['generic_part_id'],
                        'queryParams': [],
                        'rawBody': False,
                        'resource': 'generic',
                        'unwrap': 'detail',
                        'verb': 'add-member',
                        'writes': True},
 'generic create': {'bodyParams': ['name', 'part_type', 'spec', 'strictness'],
                    'httpVerb': 'POST',
                    'operationId': 'create_generic_part',
                    'params': {'name': {'required': True, 'type': 'string'},
                               'part_type': {'required': True, 'type': 'string'},
                               'spec': {'required': True, 'type': 'object'},
                               'strictness': {'required': True, 'type': 'object'}},
                    'path': '/v1/generic-parts',
                    'pathParams': [],
                    'queryParams': [],
                    'rawBody': False,
                    'resource': 'generic',
                    'unwrap': 'detail',
                    'verb': 'create',
                    'writes': True},
 'generic create-saved-search': {'bodyParams': ['frozen_members',
                                                'name',
                                                'search_text',
                                                'tag_state'],
                                 'httpVerb': 'POST',
                                 'operationId': 'create_saved_search',
                                 'params': {'frozen_members': {'required': False, 'type': 'array'},
                                            'generic_part_id': {'required': True, 'type': 'string'},
                                            'name': {'required': True, 'type': 'string'},
                                            'search_text': {'required': False, 'type': 'string'},
                                            'tag_state': {'required': True, 'type': 'object'}},
                                 'path': '/v1/generic-parts/{generic_part_id}/saved-searches',
                                 'pathParams': ['generic_part_id'],
                                 'queryParams': [],
                                 'rawBody': False,
                                 'resource': 'generic',
                                 'unwrap': 'detail',
                                 'verb': 'create-saved-search',
                                 'writes': True},
 'generic exclude-member': {'bodyParams': [],
                            'httpVerb': 'POST',
                            'operationId': 'exclude_generic_member',
                            'params': {'generic_part_id': {'required': True, 'type': 'string'},
                                       'part_id': {'required': True, 'type': 'string'}},
                            'path': '/v1/generic-parts/{generic_part_id}/members/{part_id}/exclude',
                            'pathParams': ['generic_part_id', 'part_id'],
                            'queryParams': [],
                            'rawBody': False,
                            'resource': 'generic',
                            'unwrap': 'detail',
                            'verb': 'exclude-member',
                            'writes': True},
 'generic list': {'bodyParams': [],
                  'httpVerb': 'GET',
                  'operationId': 'list_generic_parts',
                  'params': {},
                  'path': '/v1/generic-parts',
                  'pathParams': [],
                  'queryParams': [],
                  'rawBody': False,
                  'resource': 'generic',
                  'unwrap': None,
                  'verb': 'list',
                  'writes': False},
 'generic list-member-reviews': {'bodyParams': [],
                                 'httpVerb': 'GET',
                                 'operationId': 'list_generic_member_reviews',
                                 'params': {'generic_part_id': {'required': True,
                                                                'type': 'string'}},
                                 'path': '/v1/generic-parts/{generic_part_id}/reviews',
                                 'pathParams': ['generic_part_id'],
                                 'queryParams': [],
                                 'rawBody': False,
                                 'resource': 'generic',
                                 'unwrap': None,
                                 'verb': 'list-member-reviews',
                                 'writes': False},
 'generic list-saved-searches': {'bodyParams': [],
                                 'httpVerb': 'GET',
                                 'operationId': 'list_saved_searches',
                                 'params': {'generic_part_id': {'required': True,
                                                                'type': 'string'}},
                                 'path': '/v1/generic-parts/{generic_part_id}/saved-searches',
                                 'pathParams': ['generic_part_id'],
                                 'queryParams': [],
                                 'rawBody': False,
                                 'resource': 'generic',
                                 'unwrap': None,
                                 'verb': 'list-saved-searches',
                                 'writes': False},
 'generic remove-member': {'bodyParams': [],
                           'httpVerb': 'DELETE',
                           'operationId': 'remove_generic_member',
                           'params': {'generic_part_id': {'required': True, 'type': 'string'},
                                      'part_id': {'required': True, 'type': 'string'}},
                           'path': '/v1/generic-parts/{generic_part_id}/members/{part_id}',
                           'pathParams': ['generic_part_id', 'part_id'],
                           'queryParams': [],
                           'rawBody': False,
                           'resource': 'generic',
                           'unwrap': 'detail',
                           'verb': 'remove-member',
                           'writes': True},
 'generic review-member': {'bodyParams': ['acknowledge_rejection',
                                          'approval',
                                          'asserted_by',
                                          'rationale',
                                          'spec_deltas'],
                           'httpVerb': 'POST',
                           'operationId': 'review_generic_member',
                           'params': {'acknowledge_rejection': {'required': False,
                                                                'type': 'boolean'},
                                      'approval': {'required': True, 'type': 'string'},
                                      'asserted_by': {'required': False, 'type': 'string'},
                                      'generic_part_id': {'required': True, 'type': 'string'},
                                      'part_id': {'required': True, 'type': 'string'},
                                      'rationale': {'required': False, 'type': 'string'},
                                      'spec_deltas': {'required': False, 'type': 'array'}},
                           'path': '/v1/generic-parts/{generic_part_id}/members/{part_id}/review',
                           'pathParams': ['generic_part_id', 'part_id'],
                           'queryParams': [],
                           'rawBody': False,
                           'resource': 'generic',
                           'unwrap': 'detail',
                           'verb': 'review-member',
                           'writes': True},
 'generic set-preferred-member': {'bodyParams': [],
                                  'httpVerb': 'PUT',
                                  'operationId': 'set_preferred_member',
                                  'params': {'generic_part_id': {'required': True,
                                                                 'type': 'string'},
                                             'part_id': {'required': True, 'type': 'string'}},
                                  'path': '/v1/generic-parts/{generic_part_id}/members/{part_id}/preferred',
                                  'pathParams': ['generic_part_id', 'part_id'],
                                  'queryParams': [],
                                  'rawBody': False,
                                  'resource': 'generic',
                                  'unwrap': 'detail',
                                  'verb': 'set-preferred-member',
                                  'writes': True},
 'generic update': {'bodyParams': ['name', 'spec', 'strictness'],
                    'httpVerb': 'PUT',
                    'operationId': 'update_generic_part',
                    'params': {'generic_part_id': {'required': True, 'type': 'string'},
                               'name': {'required': True, 'type': 'string'},
                               'spec': {'required': True, 'type': 'object'},
                               'strictness': {'required': True, 'type': 'object'}},
                    'path': '/v1/generic-parts/{generic_part_id}',
                    'pathParams': ['generic_part_id'],
                    'queryParams': [],
                    'rawBody': False,
                    'resource': 'generic',
                    'unwrap': 'detail',
                    'verb': 'update',
                    'writes': True},
 'import detect-columns': {'bodyParams': ['headers'],
                           'httpVerb': 'POST',
                           'operationId': 'detect_columns',
                           'params': {'headers': {'required': True, 'type': 'array'}},
                           'path': '/v1/import/detect-columns',
                           'pathParams': [],
                           'queryParams': [],
                           'rawBody': False,
                           'resource': 'import',
                           'unwrap': None,
                           'verb': 'detect-columns',
                           'writes': True},
 'import match-part': {'bodyParams': ['manufacturer', 'mpn'],
                       'httpVerb': 'POST',
                       'operationId': 'match_part',
                       'params': {'manufacturer': {'required': False, 'type': 'string'},
                                  'mpn': {'required': True, 'type': 'string'}},
                       'path': '/v1/import/match-part',
                       'pathParams': [],
                       'queryParams': [],
                       'rawBody': False,
                       'resource': 'import',
                       'unwrap': None,
                       'verb': 'match-part',
                       'writes': True},
 'import ocr-engine-available': {'bodyParams': [],
                                 'httpVerb': 'GET',
                                 'operationId': 'ocr_engine_available',
                                 'params': {},
                                 'path': '/v1/import/ocr/available',
                                 'pathParams': [],
                                 'queryParams': [],
                                 'rawBody': False,
                                 'resource': 'import',
                                 'unwrap': 'available',
                                 'verb': 'ocr-engine-available',
                                 'writes': False},
 'import ocr-overlay': {'bodyParams': ['file_b64', 'file_name', 'template'],
                        'httpVerb': 'POST',
                        'operationId': 'ocr_overlay',
                        'params': {'file_b64': {'required': True, 'type': 'string'},
                                   'file_name': {'required': True, 'type': 'string'},
                                   'template': {'required': False, 'type': 'string'}},
                        'path': '/v1/import/ocr',
                        'pathParams': [],
                        'queryParams': [],
                        'rawBody': False,
                        'resource': 'import',
                        'unwrap': None,
                        'verb': 'ocr-overlay',
                        'writes': True},
 'import parse-source': {'bodyParams': ['file_b64', 'file_name', 'path', 'template'],
                         'httpVerb': 'POST',
                         'operationId': 'parse_import_source',
                         'params': {'file_b64': {'required': False, 'type': 'string'},
                                    'file_name': {'required': False, 'type': 'string'},
                                    'path': {'required': False, 'type': 'string'},
                                    'template': {'required': False, 'type': 'string'}},
                         'path': '/v1/import/parse',
                         'pathParams': [],
                         'queryParams': [],
                         'rawBody': False,
                         'resource': 'import',
                         'unwrap': None,
                         'verb': 'parse-source',
                         'writes': True},
 'parts adjust': {'bodyParams': ['adj_type', 'note', 'quantity', 'source'],
                  'httpVerb': 'POST',
                  'operationId': 'adjust_part',
                  'params': {'adj_type': {'required': True, 'type': 'string'},
                             'note': {'required': False, 'type': 'string'},
                             'part_key': {'required': True, 'type': 'string'},
                             'quantity': {'required': True, 'type': 'integer'},
                             'source': {'required': False, 'type': 'string'}},
                  'path': '/v1/parts/{part_key}/adjust',
                  'pathParams': ['part_key'],
                  'queryParams': [],
                  'rawBody': False,
                  'resource': 'parts',
                  'unwrap': 'detail',
                  'verb': 'adjust',
                  'writes': True},
 'parts delete': {'bodyParams': [],
                  'httpVerb': 'DELETE',
                  'operationId': 'delete_part',
                  'params': {'part_key': {'required': True, 'type': 'string'}},
                  'path': '/v1/parts/{part_key}',
                  'pathParams': ['part_key'],
                  'queryParams': [],
                  'rawBody': False,
                  'resource': 'parts',
                  'unwrap': 'detail',
                  'verb': 'delete',
                  'writes': True},
 'parts evaluate-predicates': {'bodyParams': ['package', 'predicates', 'prefer'],
                               'httpVerb': 'POST',
                               'operationId': 'evaluate_part_predicates',
                               'params': {'package': {'required': False, 'type': 'string'},
                                          'part_key': {'required': True, 'type': 'string'},
                                          'predicates': {'required': False, 'type': 'array'},
                                          'prefer': {'required': False, 'type': 'array'}},
                               'path': '/v1/parts/{part_key}/evaluate',
                               'pathParams': ['part_key'],
                               'queryParams': [],
                               'rawBody': False,
                               'resource': 'parts',
                               'unwrap': None,
                               'verb': 'evaluate-predicates',
                               'writes': True},
 'parts extract-spec': {'bodyParams': [],
                        'httpVerb': 'GET',
                        'operationId': 'extract_spec',
                        'params': {'part_key': {'required': True, 'type': 'string'}},
                        'path': '/v1/parts/{part_key}/spec',
                        'pathParams': ['part_key'],
                        'queryParams': [],
                        'rawBody': False,
                        'resource': 'parts',
                        'unwrap': 'spec',
                        'verb': 'extract-spec',
                        'writes': False},
 'parts fetch-missing-descriptions': {'bodyParams': [],
                                      'httpVerb': 'POST',
                                      'operationId': 'fetch_missing_descriptions',
                                      'params': {},
                                      'path': '/v1/parts/fetch-missing-descriptions',
                                      'pathParams': [],
                                      'queryParams': [],
                                      'rawBody': False,
                                      'resource': 'parts',
                                      'unwrap': 'detail',
                                      'verb': 'fetch-missing-descriptions',
                                      'writes': True},
 'parts get-attributes': {'bodyParams': [],
                          'httpVerb': 'GET',
                          'operationId': 'get_part_attributes',
                          'params': {'part_key': {'required': True, 'type': 'string'}},
                          'path': '/v1/parts/{part_key}/attributes',
                          'pathParams': ['part_key'],
                          'queryParams': [],
                          'rawBody': False,
                          'resource': 'parts',
                          'unwrap': None,
                          'verb': 'get-attributes',
                          'writes': False},
 'parts get-generic-group-names': {'bodyParams': [],
                                   'httpVerb': 'GET',
                                   'operationId': 'get_generic_group_names',
                                   'params': {'part_key': {'required': True, 'type': 'string'}},
                                   'path': '/v1/parts/{part_key}/groups',
                                   'pathParams': ['part_key'],
                                   'queryParams': [],
                                   'rawBody': False,
                                   'resource': 'parts',
                                   'unwrap': 'groups',
                                   'verb': 'get-generic-group-names',
                                   'writes': False},
 'parts get-history': {'bodyParams': [],
                       'httpVerb': 'GET',
                       'operationId': 'get_part_history',
                       'params': {'part_key': {'required': True, 'type': 'string'}},
                       'path': '/v1/parts/{part_key}/history',
                       'pathParams': ['part_key'],
                       'queryParams': [],
                       'rawBody': False,
                       'resource': 'parts',
                       'unwrap': None,
                       'verb': 'get-history',
                       'writes': False},
 'parts get-last-po-quantity': {'bodyParams': [],
                                'httpVerb': 'GET',
                                'operationId': 'get_last_po_quantity',
                                'params': {'part_key': {'required': True, 'type': 'string'}},
                                'path': '/v1/parts/{part_key}/last-po-quantity',
                                'pathParams': ['part_key'],
                                'queryParams': [],
                                'rawBody': False,
                                'resource': 'parts',
                                'unwrap': 'quantity',
                                'verb': 'get-last-po-quantity',
                                'writes': False},
 'parts get-price-summary': {'bodyParams': [],
                             'httpVerb': 'GET',
                             'operationId': 'get_price_summary',
                             'params': {'part_key': {'required': True, 'type': 'string'}},
                             'path': '/v1/parts/{part_key}/prices',
                             'pathParams': ['part_key'],
                             'queryParams': [],
                             'rawBody': False,
                             'resource': 'parts',
                             'unwrap': None,
                             'verb': 'get-price-summary',
                             'writes': False},
 'parts get-sourced-distributors': {'bodyParams': [],
                                    'httpVerb': 'GET',
                                    'operationId': 'get_sourced_distributors',
                                    'params': {'part_key': {'required': True, 'type': 'string'}},
                                    'path': '/v1/parts/{part_key}/distributors',
                                    'pathParams': ['part_key'],
                                    'queryParams': [],
                                    'rawBody': False,
                                    'resource': 'parts',
                                    'unwrap': None,
                                    'verb': 'get-sourced-distributors',
                                    'writes': False},
 'parts has-purchase-history': {'bodyParams': [],
                                'httpVerb': 'GET',
                                'operationId': 'has_purchase_history',
                                'params': {'part_key': {'required': True, 'type': 'string'}},
                                'path': '/v1/parts/{part_key}/purchase-history',
                                'pathParams': ['part_key'],
                                'queryParams': [],
                                'rawBody': False,
                                'resource': 'parts',
                                'unwrap': 'has_purchase_history',
                                'verb': 'has-purchase-history',
                                'writes': False},
 'parts list': {'bodyParams': [],
                'httpVerb': 'GET',
                'operationId': 'list_parts',
                'params': {},
                'path': '/v1/parts',
                'pathParams': [],
                'queryParams': [],
                'rawBody': False,
                'resource': 'parts',
                'unwrap': 'inventory',
                'verb': 'list',
                'writes': False},
 'parts record-fetched-prices': {'bodyParams': ['distributor',
                                                'packagings',
                                                'price_tiers',
                                                'reel_fee',
                                                'reel_qty'],
                                 'httpVerb': 'POST',
                                 'operationId': 'record_fetched_prices',
                                 'params': {'distributor': {'required': True, 'type': 'string'},
                                            'packagings': {'required': False, 'type': 'array'},
                                            'part_key': {'required': True, 'type': 'string'},
                                            'price_tiers': {'required': True, 'type': 'array'},
                                            'reel_fee': {'required': False, 'type': 'number'},
                                            'reel_qty': {'required': False, 'type': 'integer'}},
                                 'path': '/v1/parts/{part_key}/fetched-prices',
                                 'pathParams': ['part_key'],
                                 'queryParams': [],
                                 'rawBody': False,
                                 'resource': 'parts',
                                 'unwrap': 'detail',
                                 'verb': 'record-fetched-prices',
                                 'writes': True},
 'parts update-fields': {'bodyParams': ['fields'],
                         'httpVerb': 'PATCH',
                         'operationId': 'update_part_fields',
                         'params': {'fields': {'required': True, 'type': 'object'},
                                    'part_key': {'required': True, 'type': 'string'}},
                         'path': '/v1/parts/{part_key}',
                         'pathParams': ['part_key'],
                         'queryParams': [],
                         'rawBody': False,
                         'resource': 'parts',
                         'unwrap': 'detail',
                         'verb': 'update-fields',
                         'writes': True},
 'parts update-price': {'bodyParams': ['ext_price', 'unit_price'],
                        'httpVerb': 'PUT',
                        'operationId': 'update_part_price',
                        'params': {'ext_price': {'required': False, 'type': 'number'},
                                   'part_key': {'required': True, 'type': 'string'},
                                   'unit_price': {'required': False, 'type': 'number'}},
                        'path': '/v1/parts/{part_key}/price',
                        'pathParams': ['part_key'],
                        'queryParams': [],
                        'rawBody': False,
                        'resource': 'parts',
                        'unwrap': 'detail',
                        'verb': 'update-price',
                        'writes': True},
 'pnp consume': {'bodyParams': ['part_id', 'qty'],
                 'httpVerb': 'POST',
                 'operationId': 'pnp_consume',
                 'params': {'part_id': {'required': True, 'type': 'string'},
                            'qty': {'required': False, 'type': 'integer'}},
                 'path': '/v1/pnp/consume',
                 'pathParams': [],
                 'queryParams': [],
                 'rawBody': False,
                 'resource': 'pnp',
                 'unwrap': None,
                 'verb': 'consume',
                 'writes': True},
 'po create-with-items': {'bodyParams': ['line_items',
                                         'notes',
                                         'purchase_date',
                                         'source_file_b64',
                                         'source_file_name',
                                         'vendor_id'],
                          'httpVerb': 'POST',
                          'operationId': 'create_purchase_order_with_items',
                          'params': {'line_items': {'required': False, 'type': 'array'},
                                     'notes': {'required': False, 'type': 'string'},
                                     'purchase_date': {'required': False, 'type': 'string'},
                                     'source_file_b64': {'required': False, 'type': 'string'},
                                     'source_file_name': {'required': False, 'type': 'string'},
                                     'vendor_id': {'required': True, 'type': 'string'}},
                          'path': '/v1/purchase-orders',
                          'pathParams': [],
                          'queryParams': [],
                          'rawBody': False,
                          'resource': 'po',
                          'unwrap': 'detail',
                          'verb': 'create-with-items',
                          'writes': True},
 'po delete': {'bodyParams': [],
               'httpVerb': 'DELETE',
               'operationId': 'delete_purchase_order',
               'params': {'po_id': {'required': True, 'type': 'string'}},
               'path': '/v1/purchase-orders/{po_id}',
               'pathParams': ['po_id'],
               'queryParams': [],
               'rawBody': False,
               'resource': 'po',
               'unwrap': 'detail',
               'verb': 'delete',
               'writes': True},
 'po delete-last': {'bodyParams': [],
                    'httpVerb': 'DELETE',
                    'operationId': 'delete_last_purchase_order',
                    'params': {},
                    'path': '/v1/purchase-orders/last',
                    'pathParams': [],
                    'queryParams': [],
                    'rawBody': False,
                    'resource': 'po',
                    'unwrap': 'detail',
                    'verb': 'delete-last',
                    'writes': True},
 'po get-source': {'bodyParams': [],
                   'httpVerb': 'GET',
                   'operationId': 'get_po_source',
                   'params': {'po_id': {'required': True, 'type': 'string'}},
                   'path': '/v1/purchase-orders/{po_id}/source',
                   'pathParams': ['po_id'],
                   'queryParams': [],
                   'rawBody': False,
                   'resource': 'po',
                   'unwrap': None,
                   'verb': 'get-source',
                   'writes': False},
 'po get-source-preview': {'bodyParams': [],
                           'httpVerb': 'GET',
                           'operationId': 'get_po_source_preview',
                           'params': {'po_id': {'required': True, 'type': 'string'}},
                           'path': '/v1/purchase-orders/{po_id}/preview',
                           'pathParams': ['po_id'],
                           'queryParams': [],
                           'rawBody': False,
                           'resource': 'po',
                           'unwrap': None,
                           'verb': 'get-source-preview',
                           'writes': False},
 'po get-with-items': {'bodyParams': [],
                       'httpVerb': 'GET',
                       'operationId': 'get_po_with_items',
                       'params': {'po_id': {'required': True, 'type': 'string'}},
                       'path': '/v1/purchase-orders/{po_id}',
                       'pathParams': ['po_id'],
                       'queryParams': [],
                       'rawBody': False,
                       'resource': 'po',
                       'unwrap': None,
                       'verb': 'get-with-items',
                       'writes': False},
 'po list': {'bodyParams': [],
             'httpVerb': 'GET',
             'operationId': 'list_purchase_orders',
             'params': {},
             'path': '/v1/purchase-orders',
             'pathParams': [],
             'queryParams': [],
             'rawBody': False,
             'resource': 'po',
             'unwrap': None,
             'verb': 'list',
             'writes': False},
 'po update': {'bodyParams': ['notes', 'purchase_date', 'vendor_id'],
               'httpVerb': 'PATCH',
               'operationId': 'update_purchase_order',
               'params': {'notes': {'required': False, 'type': 'string'},
                          'po_id': {'required': True, 'type': 'string'},
                          'purchase_date': {'required': False, 'type': 'string'},
                          'vendor_id': {'required': False, 'type': 'string'}},
               'path': '/v1/purchase-orders/{po_id}',
               'pathParams': ['po_id'],
               'queryParams': [],
               'rawBody': False,
               'resource': 'po',
               'unwrap': 'detail',
               'verb': 'update',
               'writes': True},
 'preferences load': {'bodyParams': [],
                      'httpVerb': 'GET',
                      'operationId': 'load_preferences',
                      'params': {},
                      'path': '/v1/preferences',
                      'pathParams': [],
                      'queryParams': [],
                      'rawBody': False,
                      'resource': 'preferences',
                      'unwrap': None,
                      'verb': 'load',
                      'writes': False},
 'preferences save': {'bodyParams': [],
                      'httpVerb': 'PUT',
                      'operationId': 'save_preferences',
                      'params': {},
                      'path': '/v1/preferences',
                      'pathParams': [],
                      'queryParams': [],
                      'rawBody': True,
                      'resource': 'preferences',
                      'unwrap': None,
                      'verb': 'save',
                      'writes': True},
 'purchases import': {'bodyParams': ['rows'],
                      'httpVerb': 'POST',
                      'operationId': 'import_purchases',
                      'params': {'rows': {'required': True, 'type': 'array'}},
                      'path': '/v1/purchases/import',
                      'pathParams': [],
                      'queryParams': [],
                      'rawBody': False,
                      'resource': 'purchases',
                      'unwrap': 'detail',
                      'verb': 'import',
                      'writes': True},
 'purchases remove-last': {'bodyParams': [],
                           'httpVerb': 'DELETE',
                           'operationId': 'remove_last_purchases',
                           'params': {'count': {'required': True, 'type': 'integer'}},
                           'path': '/v1/purchases/last',
                           'pathParams': [],
                           'queryParams': ['count'],
                           'rawBody': False,
                           'resource': 'purchases',
                           'unwrap': 'detail',
                           'verb': 'remove-last',
                           'writes': True},
 'saved-search delete': {'bodyParams': [],
                         'httpVerb': 'DELETE',
                         'operationId': 'delete_saved_search',
                         'params': {'search_id': {'required': True, 'type': 'string'}},
                         'path': '/v1/saved-searches/{search_id}',
                         'pathParams': ['search_id'],
                         'queryParams': [],
                         'rawBody': False,
                         'resource': 'saved-search',
                         'unwrap': 'detail',
                         'verb': 'delete',
                         'writes': True},
 'scan start-session': {'bodyParams': ['template'],
                        'httpVerb': 'POST',
                        'operationId': 'start_scan_session',
                        'params': {'template': {'required': False, 'type': 'string'}},
                        'path': '/v1/scan/sessions',
                        'pathParams': [],
                        'queryParams': [],
                        'rawBody': False,
                        'resource': 'scan',
                        'unwrap': None,
                        'verb': 'start-session',
                        'writes': True},
 'spec extract-from-value': {'bodyParams': ['package_str', 'part_type', 'value_str'],
                             'httpVerb': 'POST',
                             'operationId': 'extract_spec_from_value',
                             'params': {'package_str': {'required': True, 'type': 'string'},
                                        'part_type': {'required': True, 'type': 'string'},
                                        'value_str': {'required': True, 'type': 'string'}},
                             'path': '/v1/spec/extract',
                             'pathParams': [],
                             'queryParams': [],
                             'rawBody': False,
                             'resource': 'spec',
                             'unwrap': None,
                             'verb': 'extract-from-value',
                             'writes': True},
 'vendors delete': {'bodyParams': [],
                    'httpVerb': 'DELETE',
                    'operationId': 'delete_vendor',
                    'params': {'vendor_id': {'required': True, 'type': 'string'}},
                    'path': '/v1/vendors/{vendor_id}',
                    'pathParams': ['vendor_id'],
                    'queryParams': [],
                    'rawBody': False,
                    'resource': 'vendors',
                    'unwrap': 'detail',
                    'verb': 'delete',
                    'writes': True},
 'vendors fetch-favicon': {'bodyParams': ['url'],
                           'httpVerb': 'POST',
                           'operationId': 'fetch_favicon',
                           'params': {'url': {'required': True, 'type': 'string'}},
                           'path': '/v1/vendors/favicon',
                           'pathParams': [],
                           'queryParams': [],
                           'rawBody': False,
                           'resource': 'vendors',
                           'unwrap': 'path',
                           'verb': 'fetch-favicon',
                           'writes': True},
 'vendors list': {'bodyParams': [],
                  'httpVerb': 'GET',
                  'operationId': 'list_vendors',
                  'params': {},
                  'path': '/v1/vendors',
                  'pathParams': [],
                  'queryParams': [],
                  'rawBody': False,
                  'resource': 'vendors',
                  'unwrap': None,
                  'verb': 'list',
                  'writes': False},
 'vendors merge': {'bodyParams': ['dst_id', 'src_id'],
                   'httpVerb': 'POST',
                   'operationId': 'merge_vendors',
                   'params': {'dst_id': {'required': True, 'type': 'string'},
                              'src_id': {'required': True, 'type': 'string'}},
                   'path': '/v1/vendors/merge',
                   'pathParams': [],
                   'queryParams': [],
                   'rawBody': False,
                   'resource': 'vendors',
                   'unwrap': 'detail',
                   'verb': 'merge',
                   'writes': True},
 'vendors update': {'bodyParams': ['favicon_path', 'name', 'url', 'vendor_id'],
                    'httpVerb': 'PUT',
                    'operationId': 'update_vendor',
                    'params': {'favicon_path': {'required': False, 'type': 'string'},
                               'name': {'required': False, 'type': 'string'},
                               'url': {'required': False, 'type': 'string'},
                               'vendor_id': {'required': False, 'type': 'string'}},
                    'path': '/v1/vendors',
                    'pathParams': [],
                    'queryParams': [],
                    'rawBody': False,
                    'resource': 'vendors',
                    'unwrap': 'detail',
                    'verb': 'update',
                    'writes': True},
 'warnings get': {'bodyParams': [],
                  'httpVerb': 'GET',
                  'operationId': 'get_warnings',
                  'params': {},
                  'path': '/v1/warnings',
                  'pathParams': [],
                  'queryParams': [],
                  'rawBody': False,
                  'resource': 'warnings',
                  'unwrap': None,
                  'verb': 'get',
                  'writes': False}}
